name: trading_website
description: "SolArena - 1v1 Competitive Trading Game on Solana"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # State management
  flutter_riverpod: ^3.2.1

  # Routing
  flutter_svg: ^2.2.3
  go_router: ^17.1.0

  # UI / Design
  google_fonts: ^8.0.1
  qr_flutter: ^4.1.0

  # Networking
  http: ^1.2.0

  # Utilities
  intl: ^0.20.2
  pointer_interceptor: ^0.10.1+2
  url_launcher: ^6.3.0
  web: ^1.1.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/wallets/
